name: Build Wheel
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install setuptools wheel pybind11
      
    - name: Build Wheel
      run: pip wheel ./pyclothoids --no-deps -w wheels/
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Usa la versione v4
      if: success()  # Opzionale: carica solo se i passi precedenti hanno successo
      with:
        name: pyclothoids-wheel
        path: wheels/
